language: c
os: osx

env:
    global:
        - CODECOV_TOKEN="6b2be568-f634-4f85-8149-6c1728c85921"
branches:
    only:
        - master

before_script:
    - make test
script:
    - ./test "hello"
after_success:
    - make gcov
    - bash <(curl -s https://codecov.io/bash) -X gcov
