language: c
os: osx
sudo: true
env:
    global:
        - CODECOV_TOKEN="6b2be568-f634-4f85-8149-6c1728c85921"
        - HOMEBREW_NO_AUTO_UPDATE=1
        - CPATH=/Users/$HOME/.brew/include:$CPATH
        - LIBRARY_PATH=/Users/$HOME/.brew/lib:$LIBRARY_PATH
branches:
    only:
        - master
install:
    - git clone https://github.com/thijsdejong/codam-norminette-plus ~/norminette+
before_script:
    - make test COV=1
script:
    - ~/norminette+/run.py
